### ISSUE TITLE
Minitest Features Support?

### ISSUE THREAD

**Issue by ipstatic** [tpope/vim-rails#415]
I have a few feature tests located in test/features/*_test.rb. Whenever I try to run them via :Rake or :.Rake, I get the following:

```
rake aborted!
LoadError: cannot load such file -- /Users/ipstatic/Repos/hello_world/test/features
/Users/ipstatic/.gem/ruby/2.1.3/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/Users/ipstatic/.gem/ruby/2.1.3/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/ipstatic/.gem/ruby/2.1.3/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/ipstatic/.gem/ruby/2.1.3/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/Users/ipstatic/.gem/ruby/2.1.3/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:114:in `block (3 levels) in define'
/Users/ipstatic/.gem/ruby/2.1.3/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:114:in `each'
/Users/ipstatic/.gem/ruby/2.1.3/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:114:in `block (2 levels) in define'
/Users/ipstatic/.gem/ruby/2.1.3/gems/railties-4.2.1/lib/rails/test_unit/sub_test_task.rb:113:in `block in define'
/Users/ipstatic/.gem/ruby/2.1.3/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/Users/ipstatic/.gem/ruby/2.1.3/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
/Users/ipstatic/.gem/ruby/2.1.3/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/ipstatic/.gem/ruby/2.1.3/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
Tasks: TOP => test:units
(See full trace by running task with --trace)
```
I can run the test just fine with rake test. Are feature tests unsupported or am I doing it wrong?

**Comment by tpope** [comment]
Where are you calling `:Rake` from?

**Comment by ipstatic** [comment]
The Rails root.

**Comment by tpope** [comment]
I mean what file?

**Comment by ipstatic** [comment]
Oh, `test/features/groups_test.rb`

Here is its contents:

```
require "test_helper"

feature "Groups" do
  scenario "Can edit assigned groups" do
    visit groups_path
    page.must_have_content users(:test).email
  end
end
```

**Comment by tpope** [comment]
That should work. What rake task is it actually running?

**Comment by tpope** [comment]
Compare to `:echo rails#buffer().default_rake_task()`.

**Comment by ipstatic** [comment]
It should be trying to run rake test I believe, that is what I run from the command line.

Here is the output from `test/features/groups_test.rb`: `test:units TEST=test/features`

And the same from `test/models/group_test.rb`: `test:units TEST=test/models/group_test.rb`

If I take the malformed test/features command and complete it, it works from the command line:

`bundle exec rake test:units TEST=test/features/groups_test.rb`

**Comment by ipstatic** [comment]
It works! Thanks for your quick responses and great plugins for Vim.
